name: EDK2 ginkgo build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    - name: Update APT
      run: sudo apt update
      
    - name: Install Dependencies
      run: sudo apt install build-essential crossbuild-essential-armhf uuid-dev iasl git nasm python3-distutils python3
    
    - name: Create EDK2 workspace
      run: mkdir /home/runner/work/EDK2WorkDir
      
    - name: Clone sources
      run: |
        cd /home/runner/work/EDK2WorkDir/
        git clone https://github.com/tianocore/edk2.git -b stable/202011 --depth=1 --recursive 
        git clone https://github.com/vicenteicc2008/RedmiNote8Pkg --depth=1 edk2/RedmiNote8Pkg
  
    - name: Build BaseTools
      run: |
        cd /home/runner/work/EDK2WorkDir/edk2 
        make -C BaseTools/
    - name: Build EDK2
      run: |
        cd /home/runner/work/EDK2WorkDir/edk2 
        . /home/runner/work/EDK2WorkDir/edk2/edksetup.sh 
        GCC5_ARM_PREFIX=arm-linux-gnueabihf- build -a ARM -p RedmiNote8Pkg/RedmiNote8Pkg.dsc -t GCC5 -j$(nproc) -s -n 0
        
    - name: Create boot.img
      run: |
        cd /home/runner/work/EDK2WorkDir/edk2/Build/RedmiNote8Pkg-ARM/DEBUG_GCC5/FV 
        gzip -c < SM6125_EFI.fd >kernel
        cat /home/runner/work/EDK2WorkDir/edk2/RedmiNote8Pkg/ginkgo.dtb >>kernel
        cp kernel /home/runner/work/EDK2WorkDir/edk2/RedmiNote8Pkg/kernel
        cd /home/runner/work/EDK2WorkDir/edk2/RedmiNote8Pkg
        python3 "mkbootimg.py" --kernel "kernel" --ramdisk ramdisk --kernel_offset 0x00000000 --ramdisk_offset 0x00000000 --tags_offset 0x00000000 --os_version "9.0.0" --os_patch_level "2020-11" --header_version 2 -o "/home/runner/work/EDK2WorkDir/boot-ginkgo.img" 

    - uses: actions/upload-artifact@v3
      with:
       name: boot-ginkgo.img
       path: /home/runner/work/EDK2WorkDir/boot-ginkgo.img
